export const GAME_CONFIG = Object.freeze({
  simulationHz: 60,
  fixedDeltaMs: 1000 / 60,
  maxCatchUpSteps: 5,
  maxDeltaMs: 100,
  worldWidth: 1280,
  worldHeight: 720,
  gravity: 0.82,
  maxHorizontalVelocity: 24,
  maxVerticalVelocity: 27,
  terminalVelocity: 23,
  groundFriction: 0.78,
  airFriction: 0.985,
  directionThreshold: 0.42,
  fastFallThreshold: 0.68,
  inputBufferFrames: 7,
  jumpBufferFrames: 7,
  coyoteFrames: 5,
  maxChargeFrames: 36,
  dodgeInvulnerabilityFrames: 11,
  dodgeDurationFrames: 20,
  dodgeCooldownFrames: 52,
  repeatedDodgePenaltyFrames: 18,
  respawnDelayFrames: 80,
  respawnInvulnerabilityFrames: 105,
  maxHitstunFrames: 72,
  comboEscapeAfterHits: 5,
  comboDecayFrames: 75,
  matchFrames: 150 * 60,
  suddenDeathFrames: 18 * 60,
  startingStocks: 3,
  maxDamage: 999,
  maxKnockback: 27,
  killPauseFrames: 18,
  platformDropFrames: 11,
  projectileLimitGlobal: 8,
  cameraMinZoom: 0.72,
  cameraMaxZoom: 1.05,
  renderDprCap: 2,
});

export type GameConfig = typeof GAME_CONFIG;
